version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "5004:5004"
      - "5005:5005"
      - "5006:5006"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development  # Optional: for development mode
    depends_on:
      - db

  db:
    image: postgres:13
    restart: unless-stopped
    container_name: db
    environment:
      POSTGRES_USER: fnas
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
